### ISSUE TITLE
ReferenceError: XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-js-client#149]
## Steps to reproduce:
1. `npm i fxa-js-client -S`
2. Add the following code to a file:
    ```js
    var FxaClient = require('fxa-js-client')

    var client = new FxaClient()
    console.log(client)
```

## Actual results
```
$ node test.js

/Users/pdehaan/dev/github/restmail-autoauth/node_modules/fxa-js-client/client/lib/request.js:23
    this.xhr = xhr || XMLHttpRequest;
                      ^
ReferenceError: XMLHttpRequest is not defined
    at new Request (/Users/pdehaan/dev/github/restmail-autoauth/node_modules/fxa-js-client/client/lib/request.js:23:23)
    at NodeFxAccountClient.FxAccountClient (/Users/pdehaan/dev/github/restmail-autoauth/node_modules/fxa-js-client/client/FxAccountClient.js:41:20)
    at new NodeFxAccountClient (/Users/pdehaan/dev/github/restmail-autoauth/node_modules/fxa-js-client/node/index.js:29:19)
    at Object.<anonymous> (/Users/pdehaan/dev/github/restmail-autoauth/test.js:3:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

**Comment by vladikoff** [comment]
Strange.... :mag:

**Comment by vladikoff** [comment]
Should work if
```
var FxaClient = require('fxa-js-client')

var client = new FxaClient('http://some.com')
console.log(client)
```

**Comment by pdehaan** [comment]
Thanks, @vladikoff, getting closer! Now I seem to be getting a 404 when trying to call `verifyCode()` API:

```
var FxaClient = require('fxa-js-client')

var client = new FxaClient('https://accounts.firefox.com')
client.verifyCode('e95de1bc884b435688bac471a175c06e', '35c40590cda48a4432f4a7e49e2fb41c').then(console.log, console.error)
console.log(client)
```

```
{ request:
   { baseUri: 'https://accounts.firefox.com/v1',
     _localtimeOffsetMsec: undefined,
     xhr:
      { [Function: XMLHttpRequest]
        __super__: [Object],
        nodejsSet: [Function],
        UNSENT: 0,
        OPENED: 1,
        HEADERS_RECEIVED: 2,
        LOADING: 3,
        DONE: 4,
        XMLHttpRequest: [Circular],
        SecurityError: [Object],
        InvalidStateError: [Object],
        NetworkError: [Object],
        XMLHttpRequestProgressEvent: [Function: XMLHttpRequestProgressEvent],
        XMLHttpRequestUpload: [Object] },
     timeout: 30000 } }
{ error: 'Unknown error',
  message: '<!doctype html>\n<!--[if lt IE 10]>       <html class="lt-ie10" dir="ltr" lang="en"> <![endif]-->\n<!--[if gte IE 10]><!--> <html dir="ltr" lang="en"> <!--<![endif]-->\n    <head>\n        <meta charset="utf-8">\n        <meta http-equiv="X-UA-Compatible" content="IE=edge">\n        <title>Firefox Accounts</title>\n        <meta name="description" content="">\n        <meta name="viewport" content="width=device-width">\n\n        <link rel="stylesheet" href="/styles/5d66bfe3.en.css">\n    </head>\n    <body class="static">\n        <div id="fox-logo"></div>\n        <div id="stage">\n            <div id="main-content" class="card">\n              <header>\n                <h1 id="fxa-404-header">Page not found</h1>\n              </header>\n\n              <section>\n                The page you requested is not found. We\'ve been notified and will fix any links that may be broken.\n              </section>\n\n              <div class="button-row">\n                <a href="/signup" class="button" id="fxa-404-home">Home</a>\n              </div>\n            </div>\n        </div>\n\n        <a id="about-mozilla" rel="author" target="_blank" href="https://www.mozilla.org/about/?utm_source=firefox-accounts&amp;utm_medium=Referral"></a>\n    </body>\n</html>\n',
  errno: 999,
  code: 404 }
```

**Comment by pdehaan** [comment]
Basically, what I'm trying to do is create a new FxA account, retrieve the email from restmail.net, get the "x-link" header, and verify the account using the fxa-js-client (so I can try writing some end-to-end tests for Pocket).

**Comment by vladikoff** [comment]
@pdehaan you need to use one of the FxA authentication server endpoints https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Firefox_Accounts/Introduction#Production

**Comment by pdehaan** [comment]
Sweet, that worked, thanks.
Looks like I'll have to do the conversion from the email's x-link URL to the appropriate auth server endpoint.

We should really just create an email domain that auto-approves the accounts (which is what I was originally planning). So basically if you used "anything+whatever@fxamail.biz" the account would be auto verified and you wouldnt need to do the restmail.net dance.
