### ISSUE TITLE
`npm run test-local` test failures

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-js-client#151]
```
group: devices
Waiting for email...
FAIL: #get (88ms)
AssertionError: expected { Object (code, errno, ...) } to be falsy
    at assert.notOk (/Users/stomlinson/development/fxa-js-client/node_modules/intern-geezer/assert.js:529:10)
    at onSettled (/Users/stomlinson/development/fxa-js-client/components/p/p.js:258:10)
    at onTick (/Users/stomlinson/development/fxa-js-client/components/p/p.js:40:4)
    at process._tickCallback (node.js:419:13)
0/1 tests passed
groupEnd: devices
```

...

```
FAIL: #accountUnlockVerifyCode (2ms)
AssertionError: expected { Object (code, errno, ...) } to be falsy
    at assert.notOk (/Users/stomlinson/development/fxa-js-client/node_modules/intern-geezer/assert.js:529:10)
    at onSettled (/Users/stomlinson/development/fxa-js-client/components/p/p.js:258:10)
    at onTick (/Users/stomlinson/development/fxa-js-client/components/p/p.js:40:4)
    at process._tickCallback (node.js:419:13)
PASS: #accountUnlockVerifyCode with no uid (1ms)
PASS: #accountUnlockVerifyCode with no code (0ms)
19/20 tests passed
```

**Comment by vladikoff** [comment]
At a glance:
The `group: devices` is the devices api that was removed, so I guess we should remove support for it. 
The second one not sure yet.
